/********************************************************************
* ../src/HitPosdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/HitPosdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableHitPosdict();
extern void G__cpp_setup_inheritanceHitPosdict();
extern void G__cpp_setup_typetableHitPosdict();
extern void G__cpp_setup_memvarHitPosdict();
extern void G__cpp_setup_globalHitPosdict();
extern void G__cpp_setup_memfuncHitPosdict();
extern void G__cpp_setup_funcHitPosdict();
extern void G__set_cpp_environmentHitPosdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HitPos.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HitPosdictLN_TClass;
extern G__linked_taginfo G__HitPosdictLN_TBuffer;
extern G__linked_taginfo G__HitPosdictLN_TMemberInspector;
extern G__linked_taginfo G__HitPosdictLN_TObject;
extern G__linked_taginfo G__HitPosdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__HitPosdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HitPosdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__HitPosdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HitPosdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__HitPosdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__HitPosdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__HitPosdictLN_HitPos;

/* STUB derived class for protected member access */
